FROM almalinux:9
#CMD ["ping","google.com"]
#ENTRYPOINT ["ping","google.com"]
ENTRYPOINT ["ping"] # we can override the CMD but not the ENTRYPOINT, here the CMD is the argument provides default value to ENTRYPOINT
CMD ["google.com"]