ARG version
FROM almalinux:${version:-8}
ARG AUTHOR="Saikumar" \
    PROJECT="ARG Dockerfile" \
    ENVIRONMENT="Development" 
RUN echo "Author is: ${AUTHOR}, project is: ${PROJECT}, environment is: ${ENVIRONMENT}"
CMD ["sleep", "200"]